services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    UnZeroUn\Datagrid\Datagrid\DatagridFactory:
        arguments:
            - '@unzeroun_sorter.factory'
            - '@Symfony\Component\Form\FormFactoryInterface'
            - '@Lexik\Bundle\FormFilterBundle\Filter\FilterBuilderUpdater'
            - !tagged admin.datagrid.type

    UnZeroUn\Datagrid\Action\ActionUrlBuilder:
        public: true

    UnZeroUn\Datagrid\Twig\Extension\DatagridExtension:
        arguments:
            - '@property_accessor'
        tags:
            - { name: twig.extension }

    Twig_Extensions_Extension_Intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - 'twig.extension'
