services:
    _defaults:
        public: false

    UnZeroUn\Datagrid\Datagrid\DatagridFactory:
        arguments:
            - '@unzeroun_sorter.factory'
            - '@Symfony\Component\Form\FormFactoryInterface'
            - '@Lexik\Bundle\FormFilterBundle\Filter\FilterBuilderUpdater'
            - !tagged admin.datagrid.type

    UnZeroUn\Datagrid\PropertyAccessor:
        class: Symfony\Component\PropertyAccess\PropertyAccessor

    UnZeroUn\Datagrid\Twig\Extension\DatagridExtension:
        arguments:
            - '@UnZeroUn\Datagrid\PropertyAccessor'
        tags:
            - { name: twig.extension }

    Twig_Extensions_Extension_Intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - 'twig.extension'